### ISSUE TITLE
Can't swap back to armor when submerged in lava

### ISSUE THREAD

**Issue by ZincTheMetal** [NimajnebEC/auto-elytra#11] opened 2024-02-14 17:16 UTC
If you press space in lava you equip the elytra but can't equip the armor again until you get out, this can be really bad in certain situations.
I assume it is related to [this](https://bugs.mojang.com/browse/MC-106879) bug

**Comment by brooke-ec** [comment] 2024-02-15 01:22
Thanks for such a thorough bug report!

This definitely seems to be caused by [MC-106879](https://bugs.mojang.com/browse/MC-106879). I should be able to patch this as part of the mod!

At the moment, your armour is only re-equipped after vanilla behavior causes you to stop flying, usually by landing on the ground. I could force your armour to be equipped when in lava, although this should be behind a configuration option as it may not be preferable in all situations...

I will let you know when this fix has been implemented!

**Closed as completed** 2024-02-15 02:36 UTC
Labels: bug

**Comment by brooke-ec** [comment] 2024-02-15 03:17
You should now be able to download the fixed version from [GitHub Releases](https://github.com/NimajnebEC/auto-elytra/releases/tag/v2.1.2-1.20.4) or [Modrinth](https://modrinth.com/mod/auto-elytra/version/2.1.2)!
